name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR }}
        logout: true
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./frequentlyMost
        file: ./frequentlyMost/Dockerfile
        push: true
